version: "3"

services:

  mongo1: &mongo
    image: mongo:7.0
    container_name: mongo1
    hostname: mongo1
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo/rs_keyfile:/etc/mongodb/pki/keyfile
      - ./mongo/data/mongo1-data/db:/data/db
      - ./mongo/data/mongo1-data/configdb:/data/configdb
    command: ["--replSet", "rs0", "--bind_ip_all", "--keyFile", "/etc/mongodb/pki/keyfile"]

  mongo2:
    <<: *mongo
    container_name: mongo2
    hostname: mongo2
    volumes:
      - ./mongo/rs_keyfile:/etc/mongodb/pki/keyfile
      - ./mongo/data/mongo2-data/db:/data/db
      - ./mongo/data/mongo2-data/configdb:/data/configdb

  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .env:/usr/routes-api/.env
    links:
      - mongo1
      - mongo2
    depends_on:
      - mongo1
      - mongo2