version: "3"

services:
  mongo1: &mongo
    image: mongo:7.0
    container_name: mongo1
    hostname: mongo1
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo/rs_keyfile:/etc/mongodb/pki/keyfile
    command:
      [
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "27017",
        "--keyFile",
        "/etc/mongodb/pki/keyfile",
      ]

  mongo2:
    <<: *mongo
    container_name: mongo2
    hostname: mongo2
    volumes:
      - ./mongo/rs_keyfile:/etc/mongodb/pki/keyfile

  app:
    image: node:18.17
    container_name: app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    links:
      - mongo1
      - mongo2
    depends_on:
      - mongo1
      - mongo2
    tty: true
    stdin_open: true
